@extends('layouts.app')

@section('content')
    <div class="content" style="max-width: 900px; margin: 0 auto;">
        <h2>System Documentation</h2>
        <p style="color: #64748b; margin-bottom: 20px;">Auto-generated by AI based on your Controller logic.</p>

        <div id="docsContainer">
            @forelse ($docs as $doc)
                <div class="card" style="margin-bottom: 20px; text-align: left;">
                    <h3 style="color: var(--primary); border-bottom: 2px solid #e2e8f0; padding-bottom: 10px;">
                        {{ $doc->class_name }}
                    </h3>
                    
                    <div style="background-color: #f8fafc; padding: 10px; margin-bottom: 15px; border-radius: 5px; font-family: monospace; font-size: 0.9rem;">
                        <strong>Source:</strong> {{ $doc->source_path }}
                    </div>

                    <!-- This renders the Markdown safely! -->
                    <div style="line-height: 1.6; color: #334155;">
                        {!! $doc->documentation_html !!}
                    </div>
                </div>
            @empty
                <div class="card" style="text-align: center; color: #dc2626;">
                    <h3>🚫 No Documentation Found</h3>
                    <p>Run <code>php artisan generate:docs</code> in your terminal to create it!</p>
                </div>
            @endforelse
        </div>
    </div>
@endsection