@extends('layouts.app')

@section('content')
    <div class="content" style="max-width: 900px; margin: 0 auto; padding: 20px;">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
            <h2>System Documentation</h2>
            <span style="background-color: #8b5cf6; color: white; padding: 5px 10px; border-radius: 5px; font-size: 0.8rem;">
                ✨ Auto-Generated by Gemini AI
            </span>
        </div>
        
        <div class="card" style="background-color: white; padding: 30px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; line-height: 1.6;">
            <!-- We use {!! !!} instead of {{ }} so Laravel renders the raw HTML tags that Gemini gives us, rather than printing them as plain text -->
            {!! $docs !!}
        </div>
    </div>
@endsection